services:
  - name: zentech-api
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__SecretKey
        value: "12345678901234561234567890123456"
      - key: Jwt__Issuer
        value: "ZentechIssuer"
      - key: Jwt__Audience
        value: "ZentechAudience"
      - key: ConnectionStrings__DefaultConnection
        value: "Server=localhost;Database=ZentechDB;User=imadd;Password=1994;Convert Zero Datetime=True;"
